window.KILLERS = [
  { name: 'Jack the Ripper', kills: 5 },
  { name: 'Ted Bundy', kills: 30 },
  { name: 'Jeffrey Dahmer', kills: 17 },
  { name: 'John Wayne Gacy', kills: 33 },
  { name: 'Gary Ridgway', kills: 49 },
  { name: 'Aileen Wuornos', kills: 7 },
  { name: 'Richard Ramirez', kills: 14 },
  { name: 'Dennis Rader (BTK)', kills: 10 },
  { name: 'David Berkowitz', kills: 6 },
  { name: 'Zodiac', kills: 5 },
  { name: 'Marco Bergamo', kills: 5 },
  { name: 'Theodore Kaczynski', kills: 3 },
  { name: 'Andrej Romanovič Čikatilo', kills: 53 },
  { name: 'Harold Shipman', kills: 218 },
  { name: 'Leonarda Cianciulli', kills: 3 },
  { name: 'Sonya Celeffi', kills: 5 },
  { name: 'Samuel Little', kills: 60 },
  { name: 'Ed Gein', kills: 2 },
  { name: 'Albert Fish', kills: 5 },
  { name: 'H.H. Holmes', kills: 27 },
  { name: 'Luigi Chiatti', kills: 2 },
  { name: 'Belle Gunness', kills: 14 },
  { name: 'Maurizio Minghella', kills: 15 },
  { name: 'Gianfranco Stevanin', kills: 6 },
  { name: 'Henry Lee Lucas', kills: 11 },
  { name: 'Wayne Williams', kills: 28 },
  { name: 'Rodney Alcala', kills: 8 },
  { name: 'Randy Kraft', kills: 16 },
  { name: 'Dean Corll', kills: 28 },
  { name: 'Joel Rifkin', kills: 17 },
  { name: 'Arthur Shawcross', kills: 14 },
  { name: 'Keith Hunter Jesperson', kills: 8 },
  { name: 'Israel Keyes', kills: 11 },
  { name: 'Robert Hansen', kills: 17 },
  { name: 'Edmund Kemper', kills: 10 },
  { name: 'Robert Lee Yates', kills: 16 },
  { name: 'Alexander Pichushkin', kills: 48 },
  { name: 'Anatoly Onoprienko', kills: 52 },
  { name: 'Paul Bernardo', kills: 3 },
  { name: 'Karla Homolka', kills: 3 },
  { name: 'Fred West', kills: 12 },
  { name: 'Rosemary West', kills: 12 },
  { name: 'Ian Brady', kills: 5 },
  { name: 'Myra Hindley', kills: 5 },
  { name: 'Robert Ben Rhoades', kills: 3 },
  { name: 'Richard Kuklinski', kills: 5 },
  { name: 'Leonard Lake', kills: 11 },
  { name: 'Charles Ng', kills: 11 },
  { name: 'Juana Barraza', kills: 16 }
];
