window.OBJECT_MATCHES = [
  { name: 'Jack The Ripper', object: 'Mantello e soprabito', special: true },
  { name: 'Donato Bilancia', object: 'Treno', special: true },
  { name: 'Erszebeth Bathory', object: 'Castello', special: true },
  { name: 'Aileen Whornos', object: 'Telefonata intercettata', special: true },
  { name: 'Jeffrey Dahmer', object: 'Frigorifero', special: true },
  { name: 'Ted Bundy', object: 'Maggiolone giallo', special: true },
  { name: 'Richard Ramirez', object: 'Denti marci', special: true },
  { name: 'Pietro Pacciani', object: 'Vibromassaggiatore', special: true },
  { name: 'Theodore Kaczynski', object: 'Polvere da sparo', special: true },
  { name: 'John Wayne Gacy', object: 'Costume da clown' },
  { name: 'Zodiac Killer', object: 'Lettere cifrate' },
  { name: 'Dennis Rader (BTK)', object: 'Nodo di corda' },
  { name: 'Green River Killer', object: 'Fiume' },
  { name: 'Golden State Killer', object: 'Maschera da sci' },
  { name: 'Ed Gein', object: 'Maschera di pelle' },
  { name: 'Albert Fish', object: 'Ago' },
  { name: 'H.H. Holmes', object: 'Hotel' },
  { name: 'Andrei Chikatilo', object: 'Binari' },
  { name: 'Harold Shipman', object: 'Camice medico' },
  { name: 'Luis Garavito', object: 'Mappa' },
  { name: 'Pedro Lopez', object: 'Braccialetto' },
  { name: 'Samuel Little', object: 'Taccuino' },
  { name: 'Gary Ridgway', object: 'Corda' },
  { name: 'David Berkowitz', object: 'Revolver' },
  { name: 'Dennis Nilsen', object: 'Valigia' },
  { name: 'Robert Pickton', object: 'Fattoria' },
  { name: 'Peter Sutcliffe', object: 'Martello' },
  { name: 'Belle Gunness', object: 'Fornace' },
  { name: 'Juana Barraza', object: 'Cavo' },
  { name: 'Rodney Alcala', object: 'Macchina fotografica' },
  { name: 'Randy Kraft', object: 'Taccuino codici' },
  { name: 'Dean Corll', object: 'Barca' },
  { name: 'Joel Rifkin', object: 'Tanica' },
  { name: 'Arthur Shawcross', object: 'Ascia' },
  { name: 'Israel Keyes', object: 'Secchio' },
  { name: 'Robert Hansen', object: 'Fucile' },
  { name: 'Edmund Kemper', object: 'Nastro audio' },
  { name: 'Wayne Williams', object: 'Ponte' },
  { name: 'Gilles de Rais', object: 'Spada' },
  { name: 'John Bunting', object: 'Barile' },
  { name: 'Fred West', object: 'Scalpello' },
  { name: 'Rosemary West', object: 'Guanti' },
  { name: 'Ian Brady', object: 'Bibbia' },
  { name: 'Myra Hindley', object: 'Cappotto' },
  { name: 'Karla Homolka', object: 'Videocassetta' },
  { name: 'Paul Bernardo', object: 'Camcorder' },
  { name: 'Charles Ng', object: 'Camper' },
  { name: 'Leonard Lake', object: 'Bunker' },
  { name: 'Richard Kuklinski', object: 'Ghiaccio' },
  { name: 'Aldo Semerari', object: 'Tessera' }
];
